<?php
defined('BASEPATH') OR exit('No direct script access allowed');

require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . '/libraries/Format.php';
use Restserver\Libraries\REST_Controller;

class apiAdopciones extends REST_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Adopciones_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('adopciones/adopciones_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Adopciones_model->json();
    }

    public function get_all_adoptions_get($id) 
    {
        $row = $this->Adopciones_model->get_by_id($id);
        if ($row) {
            $data = array(
            'IdAdopcion' => $row->IdAdopcion,
            'IdPost' => $row->IdPost,
            'IdUsuarioAdopcion' => $row->IdUsuarioAdopcion,
            'IdFormulario' => $row->IdFormulario,
            'Fecha' => $row->Fecha,
            );
            $this->load->view('adopciones/adopciones_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('adopciones'));
        }
    }
    
    public function create_Adoption_post() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'IdPost' => $this->input->post('IdPost',TRUE),
		'IdUsuarioAdopcion' => $this->input->post('IdUsuarioAdopcion',TRUE),
		'IdFormulario' => $this->input->post('IdFormulario',TRUE),
		'Fecha' => $this->input->post('Fecha',TRUE),
	    );

            $this->Adopciones_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('adopciones'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Adopciones_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('adopciones/update_action'),
		'IdAdopcion' => set_value('IdAdopcion', $row->IdAdopcion),
		'IdPost' => set_value('IdPost', $row->IdPost),
		'IdUsuarioAdopcion' => set_value('IdUsuarioAdopcion', $row->IdUsuarioAdopcion),
		'IdFormulario' => set_value('IdFormulario', $row->IdFormulario),
		'Fecha' => set_value('Fecha', $row->Fecha),
	    );
            $this->load->view('adopciones/adopciones_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('adopciones'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('IdAdopcion', TRUE));
        } else {
            $data = array(
		'IdPost' => $this->input->post('IdPost',TRUE),
		'IdUsuarioAdopcion' => $this->input->post('IdUsuarioAdopcion',TRUE),
		'IdFormulario' => $this->input->post('IdFormulario',TRUE),
		'Fecha' => $this->input->post('Fecha',TRUE),
	    );

            $this->Adopciones_model->update($this->input->post('IdAdopcion', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('adopciones'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Adopciones_model->get_by_id($id);

        if ($row) {
            $this->Adopciones_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('adopciones'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('adopciones'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('IdPost', 'idpost', 'trim|required');
	$this->form_validation->set_rules('IdUsuarioAdopcion', 'idusuarioadopcion', 'trim|required');
	$this->form_validation->set_rules('IdFormulario', 'idformulario', 'trim|required');
	$this->form_validation->set_rules('Fecha', 'fecha', 'trim|required');

	$this->form_validation->set_rules('IdAdopcion', 'IdAdopcion', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Adopciones.php */
/* Location: ./application/controllers/Adopciones.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-09-11 23:33:54 */
/* http://harviacode.com */